### ISSUE TITLE
mesa_17.1.7.bb:do_compile failed with exit code '1'

### ISSUE THREAD

**Issue by simontheu** [TechNexion/edm-yocto-bsp#11]
ERROR: Task (~/edm_yocto/sources/poky/meta/recipes-graphics/mesa/mesa_17.1.7.bb:do_compile) failed with exit code '1'

**Comment by simontheu** [comment]
Can I lock in an old version that will compile?

**Comment by francisduhaut** [comment]
Do you follow the procedure with using docker file ? I have build this bsp with issue only with v4lutils

**Comment by simontheu** [comment]
Hi,

Just trying now, it wasn’t using docker, I had a native 16.04.05 VM with all the dependencies. What could it be doing differently in the docker?

**Comment by richard-hu** [comment]
Hello, @simontheu :

Could you share the error log for mesa_17.1.7?
Our build server uses docker as build environment to generate release image.
It works fine and we don't encounter problem on compiling mesa.  

We also provide the VM based on virtualbox and the VM is validated to complete building yocto 2.4. 
ftp://ftp.technexion.net/development_resources/development_tools/vm/Build_Env_Ubuntu_x64_16.04.ova

Maybe you can give it a try.

BR,

Richard

**Comment by simontheu** [comment]
Thanks richard, I am downloading the VM
