### ISSUE TITLE
Systemd Integration

### ISSUE THREAD

**Issue by zahabshams** [TechNexion/edm-yocto-bsp#13]
Hi 
Do you provide as how to integrate systemd for Pico Nymph.

**Comment by zahabshams** [comment]
I tried doing that with yocto 2.0. But this is causing kernel panic. Please kernel panic log and local.conf
[kernelPanic-yocto2.0-pico-nymph-systemd.txt](https://github.com/TechNexion/edm-yocto-bsp/files/2997885/kernelPanic-yocto2.0-pico-nymph-systemd.txt)



[local.conf.txt](https://github.com/TechNexion/edm-yocto-bsp/files/2997876/local.conf.txt)

**Comment by richard-hu** [comment]
Hello, Zahabshams:

I didn't try Yocto 2.0 with systemd before.
Do you consider to use Yocto 2.4?
It supports systemd out of box.

BR,

Richard
