### ISSUE TITLE
Weston not displaying anything

### ISSUE THREAD

**Issue by kapollo** [TechNexion/edm-yocto-bsp#15]
Hi I'm building sumo branch for the pico-imx8m, the compilation (besides some issues with building for the machine I had, for whatever reason) goes fine, but when I try to run the image on the board, everything is just fine up to the moment when weston should kick in.
I'm getting black screen with a cursor in top-left corner and nothing else.
Weston logs show nothing special the process is running, either started with systemd or manually.
I've build both for xwayland and wayland, and the result is the same.
Do you happen to know what is going on? 
I had similar situation when I tried to port your rocko branch to sumo, by myself and I thought  I messed something up, and put it on the hook until someone (that actually knows what he/she is/are doing ;) ) fix the stuff. But now I'm stuck ...

BR

**Comment by richard-hu** [comment]
@kapollo 

Yocto 2.5 sumo for pico-imx8m(i.mx8MQ) isn't ready yet.
Currently, Yocto 2.5 is only for pico-imx8mm(i.mx8MMini).
Our next task is to add yocto 2.5 support for pico-imx8.
We plan to finish this task before end of April.

BR,

Richard

**Comment by kapollo** [comment]
@richard-hu thanks for the info
