### ISSUE TITLE
gclib fails to compile

### ISSUE THREAD

**Issue by joiie** [TechNexion/edm-yocto-bsp#2]
Wehn trying to follow the instructions here on ubuntu 16.04 LTS i glibc fails to build. Please see the attached logfiles of the error.
[log.do_compile.7947.txt](https://github.com/TechNexion/edm-yocto-bsp/files/381349/log.do_compile.7947.txt)
[20160725093559.log.txt](https://github.com/TechNexion/edm-yocto-bsp/files/381353/20160725093559.log.txt)

**Comment by richard-hu** [comment]
Hello, Joiie:

I google the error message.
It seems this error also results from "GCC 5.X"....
There is a workaround:
[https://lists.yoctoproject.org/pipermail/yocto/2015-July/025431.html](url)

modify a line in meta/recipes-core/glibc/cross-localedef-native_2.20.bb
`-CFLAGS += "-DNOT_IN_libc=1"
+CFLAGS += "-DNOT_IN_libc=1 -fgnu89-inline"

BTW, ubuntu 16.04 isn't validated yet to build Yocto 1.7.
So, we can't exclude that there will be other similar issues.

If problems still happen, we'd recommend to create an ubuntu 12.04 or 14.04 environment to build Yocto 1.7.

1. Use VMplayer to run ubuntu 12.04:
You can download it from Technexion offical FTP - 
ftp://ftp.technexion.net/development_resources/development_tools/vm/technexion_ubuntu-12.04_vm_20160604.zip

2. Use 'chroot' to create ubuntu 14.04 environment:
https://help.ubuntu.com/community/BasicChroot

3. Try to downgrade GCC 5.x to GCC 4.X in ubuntu 16.04:
http://askubuntu.com/questions/724872/downgrade-gcc-from-5-2-1-to-4-9-ubuntu-15-10

BR,

Thank You !

Richard


`

**Comment by joiie** [comment]
Cahinging to gcc (and g++) 4.7 solved most of the problems.
Also run into a problem with mklibs 0.1.39 no longer being available at the specified mirror but i found one at intel (http://iotdk.intel.com/repos/3.0/sources/x86_64-linux/mklibs-native-0.1.39-r0/mklibs-native-0.1.39-r0-patched.tar.gz)

After that it compiled mostly, am currently stuck with an u-boot error. If i don't manage to solve it i will try it with ubuntu 14.4 LTS (do you know if there is any differense in using the desktop or server version when using yocto?)

Thanks for your help and pointing me in the right direction

**Comment by richard-hu** [comment]
Hello, Joiie:

It's great to hear the good news. : )
Could you post the error message of u-boot ?
I need to figure out if this error is u-boot issue or something else.
(Actually, I'm also maintainer for Technexion u-boot... )

As your question, 
(if there is any differense in using the desktop or server version when using yocto?) ->
Do you mean the host ubuntu PC is desktop or server version ? or 
Do you mean the target yocto is built with desktop or headless ?

Thank You !

BR,

Richard

**Comment by joiie** [comment]
Hi richard-hu:
I am creating a seperate issue in your u-boot repository for the u-boot issue, in short it fails to apply a patch.
