### ISSUE TITLE
hciconfig fails to see wifi/bt module with bcm only drivers

### ISSUE THREAD

**Issue by TGunthorpe** [TechNexion/edm-yocto-bsp#21]
4.9.88-2.0.0 used to compile and support BCM modules. After a recent build, the drivers where present as expected, but hciconfig was not able to communicate with the wifi/bt module.

**Configuration script:**
WIFI_FIRMWARE=y WIFI_MODULE=brcm DISTRO=fsl-imx-fb MACHINE=pico-imx6 BASEBOARD=nymph source edm-setup-release.sh -b build-pico-imx6

**local.conf:**
MACHINE ??= 'pico-imx6'
DISTRO ?= 'fsl-imx-fb'
PACKAGE_CLASSES ?= "package_rpm"
EXTRA_IMAGE_FEATURES ?= "debug-tweaks package-management ssh-server-dropbear"
DISTRO_FEATURES_append += "bluez5 bluetooth wifi systemd journald "
IMAGE_INSTALL_append += "packagegroup-core-buildessential sudo opkg apt connman \
wget curl openssl nano git dhcp-client wireless-tools nodejs bluez5 \
python3 python3-pip python3-setuptools python3-dev python3-modules \
kernel-modules iptables wpa-supplicant i2c-tools connman-client cmake swig"
USER_CLASSES ?= "buildstats image-mklibs image-prelink"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"
PACKAGECONFIG_append_pn-qemu-native = " sdl"
PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
CONF_VERSION = "1"
BASE_BOARD ?= "nymph"
DISPLAY_INFO ?= "lcd"
RF_FIRMWARES ?= " qca "
MACHINEOVERRIDES =. "${@'' if d.getVar('RF_FIRMWARES', True) is None else '%s:' % ':'.join([fw.lower() for $
XZ_COMPRESSION_LEVEL = "-9"
XZ_INTEGRITY_CHECK = "crc64"

DL_DIR ?= "${BSPDIR}/downloads/"

**bitbake:**
bitbake core-image-base

**Comment by richard-hu** [comment]
Hello, @TGunthorpe :

Thanks for your feedback.
We ensure this issue exists in latest version of Yocto 2.4.
We are working on figuring it out.

BR.

Richard

**Comment by po-cheng-technexion** [comment]
Please update to commit 38111b4bd8d4d1ec9a09ab43dc0b1b0be1e5858c
