### ISSUE TITLE
php error becouse binutils

### ISSUE THREAD

**Issue by maku0** [TechNexion/edm-yocto-bsp#3]
Hi,
During adding php to the image i met such error when executing php in device:
root@pico-imx6:~# php
php: relocation error: php: symbol mysql_server_init, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference

I found solution: http://www.variscite.com/support-forum/viewtopic.php?t=372
Needed new version of binutils
https://github.com/varigit/meta-variscite-imx/blob/Krogoth-imx-4.1.15-var01/recipes-devtools/binutils/binutils-cross_2.26.bbappend
After these path everything works fine. Please consider update in your yocto distribution.
Best regards,
Karol

**Comment by richard-hu** [comment]
Hello, Karol:

Great work!!!
Thanks for your advice !
I will apply your fix soon.

BR,
Richard
