### ISSUE TITLE
tool chain not generated in build-x11-pico/tmp/deploy/sdk

### ISSUE THREAD

**Issue by zahabshams** [TechNexion/edm-yocto-bsp#4]
Hi 
 I am not getting tool chain file for pico-imx6 (at build-x11-pico/tmp/deploy/sdk) ie,
**poky-glibc-x86_64-meta-toolchain-cortexa9hf-vfp-neon-toolchain-1.7.sh**

Instead **fsl-imx-x11-glibc-x86_64-meta-toolchain-cortexa9hf-vfp-neon-toolchain-4.1.15-1.2.0.sh** is available.

Bit bake commands 
1. For yocto build
DISPLAY=lvds7 MACHINE=pico-imx6 BASEBOARD=nymph source edm-setup-release.sh \
-b build-x11-pico -e x11
bitbake fsl-image-qt5

2. For toolchain build
bitbake meta-toolchain

Please tell me what is the issue. I am using ubuntu 16.04

**Comment by richard-hu** [comment]
Hello, zahabshams:

Thanks for your feedback.
I'm confused about your question.
"fsl-imx-x11-glibc-x86_64-meta-toolchain-cortexa9hf-vfp-neon-toolchain-4.1.15-1.2.0.sh" is the script to install toolchain in your host PC.
So why should we have to use "poky-glibc-x86_64-meta-toolchain-cortexa9hf-vfp-neon-toolchain-1.7.sh"? 

BR,
Richard

**Comment by zahabshams** [comment]
![technexiontoolchain](https://user-images.githubusercontent.com/5366357/36748978-7604b1ea-1c1f-11e8-9be2-5b9c43cd9c5e.png)

I need the build environment for IMX6 (NOT IMX6UL)
Please refer to the attached screen shot of your guide "Yocto_2.0_BSP_Build_Guide.pdf"
fsl-imx-x11-glibc-x86_64-meta-toolchain-cortexa7hf-vfp-neon-toolchain-4.1.15-1.2.0.sh -- **For IMX6UL**
poky-glibc-x86_64-meta-toolchain-cortexa9hf-vfp-neon-toolchain-1.7.sh -- **For IMX6**

Regards
Zahab

**Comment by richard-hu** [comment]
Hello, zahabshams:

I get your point!!!
Sorry, it's my bad, this is a mistake on "Yocto_2.0_BSP_Build_Guide.pdf".
I have to correct this part.
The difference between i.mx6 and i.mx6ul is CPU architecture.
i.mx6 is based on ARM cortex-A9 and i.mx6ul is based ARM cortex-A7.
So if the generated toolchain is for cortex-A9, it's for i.mx6.

> ""fsl-imx-x11-glibc-x86_64-meta-toolchain-**cortexa9hf**-vfp-neon-toolchain-4.1.15-1.2.0.sh""
Attachment is the updated document.
[Yocto_2.0_BSP_Build_Guide.pdf](https://github.com/TechNexion/edm-yocto-bsp/files/1765470/Yocto_2.0_BSP_Build_Guide.pdf)

Thanks for pointing out the mistake~!!!

BR,

Richard
